// Wire types shared between the hub and channels (WebSocket messages)

/** channel → hub */
export type ClientMsg =
  | {
      type: 'register'
      id: string // UUID generated by the channel process (stable across reconnects)
      name?: string // requested name (omit to let the hub assign a random one; reconnects send the assigned name)
      host: string
      cwd: string
      pid: number
      ppid?: number // parent = the claude process PID; matched against activity reports from hooks
      title?: string
    }
  | { type: 'status'; title?: string; status?: string }
  | { type: 'ack'; msgId: number }
  | { type: 'ping' } // heartbeat: detects a half-open connection (e.g. silent WiFi drop)

/** hub → channel */
export type ServerMsg =
  | { type: 'registered'; id: string; name: string } // name confirmation on register / rename
  | { type: 'message'; msgId: number; from: string; content: string; ts: string }
  | { type: 'pong' } // heartbeat reply
  | { type: 'error'; error: string }

export interface SessionRow {
  id: string
  name: string
  host: string
  cwd: string
  pid: number
  claude_pid: number | null
  claude_session_id: string | null // Claude Code session id (stable across resume; reported by the SessionStart hook)
  title: string | null
  status: string | null
  activity: string | null // 'working' | 'idle' (reported by hooks)
  activity_at: string | null
  online: number
  first_seen: string
  last_seen: string
}

/** A post: a named mailbox with no session behind it — consumers poll it (see hub /api/post/*) */
export interface PostRow {
  name: string
  note: string | null
  created_at: string
  checked_at: string | null // last time a consumer checked (poll liveness)
  waiting: number // undelivered message count (computed by the API)
  watching: number // long-poll watchers connected right now (computed by the API)
}

export interface MessageRow {
  id: number
  to_name: string
  from_name: string
  content: string
  created_at: string
  delivered_at: string | null
}

export const DEFAULT_PORT = 8790
export const BROADCAST = '*'
